### ISSUE TITLE
SQFLite Implementation

### ISSUE THREAD

**Issue by ejabu** [MaikuB/incrementally_loading_listview#1]
Is this package also fit to SQFlite data fetching ?

In my case, I may have thousands of transaction records, which clearly are not required to pop all at once. 

What's your opinion ?

Thanks

**Comment by MaikuB** [comment]
Apologies for the late response. Only just seen this, not sure what happened to notifications. I've not tried it with sqflite but I don't see why not. Should be straightforward for you to try to confirm and given that you posted this over two weeks ago, you might have already done so
