### ISSUE TITLE
I think it will better to spilt the widget.

### ISSUE THREAD

**Issue by zouzhenglu** [MaikuB/incrementally_loading_listview#11]
It will better to spilt the listview and your auto load more widget.

**Comment by MaikuB** [comment]
please provide more details on what you mean as i'm not sure what you mean by the auto-load more widget. the only widget here is an augmented list view that will load more items when it reaches a certain point, which is the purpose of this package. rendering the load more state/widget is up to the consumers of the package to handle

**Comment by zouzhenglu** [comment]
I see.  You implement the listview with ListView.builder(), but if someone want to use ListView.separated() or ListView.custom() , it won't be work.
So I was considering how to implement a tool to achieve this feature.

**Comment by MaikuB** [comment]
The functionality to load more items for this package is tied to ListView.builder so really can't be separated. I've seen other approaches that listen to the scroll position. You'd need to do your own research on that depending on your case if you want to make use of other kind of list views.

**Comment by zouzhenglu** [comment]
Thank you!

**Comment by MaikuB** [comment]
No worries. I'd suggest you read this article in case you haven't seen it already as it has a different approach to loading more item https://medium.com/@KarthikPonnam/flutter-loadmore-in-listview-23820612907d

**Comment by zouzhenglu** [comment]
> No worries. I'd suggest you read this article in case you haven't seen it already as it has a different approach to loading more item https://medium.com/@KarthikPonnam/flutter-loadmore-in-listview-23820612907d
Awesome !!!

**Comment by zouzhenglu** [comment]
> No worries. I'd suggest you read this article in case you haven't seen it already as it has a different approach to loading more item https://medium.com/@KarthikPonnam/flutter-loadmore-in-listview-23820612907d

Awesome !!!
