### ISSUE TITLE
Is there anyway to remove the RxDart dependency? 

### ISSUE THREAD

**Issue by abdhoms** [MaikuB/incrementally_loading_listview#18]
I see that it uses PublishSubject. Is there any alternative for this without using RxDart? Like using StreamController perhaps?

```
 final PublishSubject<bool> _loadingMoreSubject = PublishSubject<bool>();
  Stream<bool> _loadingMoreStream;

  IncrementallyLoadingListViewState() {
    _loadingMoreStream =
        _loadingMoreSubject.switchMap((shouldLoadMore) => loadMore());
  }
```

It's just that I don't want to add RxDart to my app just for this ListView.

**Comment by MaikuB** [comment]
From memory, no but it's open source so you can try it out yourself

**Comment by boatengyeboah** [comment]
@MaikuB are you able to upgrade the rxdart dependency? I have some projects that require higher version of whats in this library.

**Comment by MaikuB** [comment]
@boatengyeboah in case you haven't seen it, there's a note in the readme that you can use dependency overrides. You can submit a PR as well
