### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by mainrs** [MaikuB/incrementally_loading_listview#2]
I can't test it out right now and am just looking for useful resources/libraries for my current project.

I am curious on how it performs with huge sets of data. Does it allocate and keep every newly generated list entry in memory? Not sure if you are familiar with the android ecosystem, but there is a component called RecyclerView that basically re-uses the UI elements and only changes the data that they display, making it super memory efficient and reduces the lag created by allocating all UI elements and keeping them alive.

Thanks!

**Comment by MaikuB** [comment]
I don't have metrics for you but it should be performant and based on what you've stated/asked, it sounds like you've not checked the documentation on the Flutter website. I'd suggest you start from there as a search would provide links like the following that would answer your question

https://flutter.io/cookbook/lists/long-lists/
https://flutter.io/flutter-for-android/#how-do-i-update-listviews-dynamically
https://docs.flutter.io/flutter/widgets/ListView-class.html

 Note that this library uses the `ListView.builder` constructor

**Comment by mainrs** [comment]
Ah I missed that one. I'm quite new to flutter :smile: Thanks you!
