### ISSUE TITLE
Rxdart conflict

### ISSUE THREAD

**Issue by GENL** [MaikuB/incrementally_loading_listview#3]
When I try to install the 0.04 version of the package in pubspec.yaml, I get this error:

Because flutter_google_places >=0.1.3 depends on rxdart ^0.19.0 and incrementally_loading_listview >=0.0.4 depends on rxdart ^0.18.1, flutter_google_places >=0.1.3 is incompatible with incrementally_loading_listview >=0.0.4.
So, because my_project depends on both incrementally_loading_listview ^0.0.4+3 and flutter_google_places ^0.1.3, version solving failed.

Do someone nkow how to fix it well? Thanks!

**Comment by MaikuB** [comment]
https://flutter.io/docs/development/packages-and-plugins/developing-packages#handling-package-interdependencies

**Comment by MaikuB** [comment]
Were you able to solve the conflict issues based on the above link?

**Comment by MaikuB** [comment]
Closing due to lack of response
