### ISSUE TITLE
Loading indicator widget

### ISSUE THREAD

**Issue by divan** [MaikuB/incrementally_loading_listview#6]
Hi,

thanks for the great library! Is it possible to specify the loading indicator widget somehow (in a `RefreshIndicator` fashion or any custom widget)? That would be really useful to display at the bottom of the list, while data is loading.

**Comment by MaikuB** [comment]
You would need to implement that yourself. Different apps may have different needs on what that indicator may look like and the placement, so I've intentionally not provided a way to notify that an indicator should be displayed. The example app has sample code on how it could be done
