### ISSUE TITLE
[Feature proposal] Conserve scroll momentum 

### ISSUE THREAD

**Issue by StefanLobbenmeier** [MaikuB/incrementally_loading_listview#7]
This is probably hard to do, but it would be very nice if you could scroll down in one big motion, stopping until hitting the last fetched entry, and then continuing to scroll down (maybe less quickly) after the remaining content has been fetched. 

I am not 100% sure how that would feel like, so I would like to have a bit of an discussion, has anyone ever seen that behaviour in another app?

**Comment by MaikuB** [comment]
I don't think I've seen anything like this. What you're suggesting seems to be very app-specific in that you'll likely need to look at doing this yourself e.g. by looking at the code used for implementing a listview and tweaking that so it behaves exactly as you want it to. This would move away from my intent of making this a generic package so I won't be looking at implementing the feature. You're more than welcome to fork the repo and tweak the code to your needs.

On the discussion front, I think you'd have more luck engaging in one via other places listed at https://flutter.dev/community

**Comment by StefanLobbenmeier** [comment]
I understand. Thanks.
